import type { Metadata } from "next";
import "./globals.css";
import * as stylex from "@stylexjs/stylex";
import Script from "next/script";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={``}>
        <div id="__jsx">
          <div dir="ltr">
            <div
              {...stylex.props(
                styles.fullWidth,
                styles.minHeightScreen,
                styles.systemFont,
                styles.display,
                styles.flexDir,
                styles.background,
                styles.color
              )}
            >
              <Header/>
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}

const styles = stylex.create({
  fullWidth: { width: "100%" },
  minHeightScreen: { minHeight: "100dvh" },
  systemFont: { fontFamily: "system-ui, sans-serif" },
  display: {display: "flex"},
  flexDir: {flexDirection: "column"},
  position: {position: "relative"},
  background: {background: "#000"},
  color: {color: "#fff"}
});
